name: corsair_scan push
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
            matrix:
                python-version: [3.7, 3.8]
        steps:
            - name: Checkout Code
              uses: actions/checkout@v1

            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                 python-version: ${{ matrix.python-version }}

            - name: Install PIP Dependencies
              run: pip install -r requirements_dev.txt

            - name: Test with Pytest
              run: python -m pytest --cov=corsair_scan --cov-report=html:coverage/${{ matrix.python-version }} --cov-fail-under=85 -o junit_family=xunit2 --junitxml=${{ matrix.python-version }}.results.xml

            - name: Upload Test results
              uses: actions/upload-artifact@master
              with:
                name: Test Results - ${{ matrix.python-version }}
                path: ${{ matrix.python-version }}.results.xml

            - name: Upload Code Coverage
              uses: actions/upload-artifact@master
              with:
                 name: Test Coverage - ${{ matrix.python-version }}
                 path: coverage/${{ matrix.python-version }}

            - name: Flake8 styles
              run: python -m flake8 ./corsair_scan

            - name: Bandit security scan
              run: python -m bandit -r ./corsair_scan

            - name: Safety dependency scan
              run: python -m safety check

            - name: Semgrep
              id: semgrep
              uses: returntocorp/semgrep-action@v1
              with:
                 config: p/r2c-ci